### ISSUE TITLE
sizzle 0.1.2 no longer works with ReadTheDocs

### ISSUE THREAD

**Issue by hippothebrave** [vsajip/sphinx_sizzle_theme#18]
Thanks for the lovely theme! 

With the new version 0.1.2, Sizzle no longer works with ReadTheDocs, a site for hosting documentation. My personal library had a requirement of sizzle >= 0.1.1. When I tried to build a ReadTheDocs page, I received the error:
`Theme error:
theme 'sizzle' doesn't have "theme" setting`
and the build failed.

My personal issue was fixed by pinning the version to 0.1.1, but I think it would be good for future versions to maintain ReadTheDocs compatibility (whatever that may mean.) I'm not sure what exactly caused the issue, though I noticed that quite a lot of Sphinx themes are no longer able to be built--maybe it has something to do with the recent Sphinx version update?

The full error I received:
```
Running Sphinx v6.2.1
making output directory... done
WARNING: html_static_path entry '_static' does not exist

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/prettycopy/envs/latest/lib/python3.11/site-packages/sphinx/theming.py", line 73, in __init__
    inherit = self.config.get('theme', 'inherit')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/.asdf/installs/python/3.11.0/lib/python3.11/configparser.py", line 796, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/.asdf/installs/python/3.11.0/lib/python3.11/configparser.py", line 1167, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'theme'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/prettycopy/envs/latest/lib/python3.11/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/prettycopy/envs/latest/lib/python3.11/site-packages/sphinx/application.py", line 268, in __init__
    self._init_builder()
  File "/home/docs/checkouts/readthedocs.org/user_builds/prettycopy/envs/latest/lib/python3.11/site-packages/sphinx/application.py", line 340, in _init_builder
    self.builder.init()
  File "/home/docs/checkouts/readthedocs.org/user_builds/prettycopy/envs/latest/lib/python3.11/site-packages/sphinx/builders/html/__init__.py", line 253, in init
    self.init_templates()
  File "/home/docs/checkouts/readthedocs.org/user_builds/prettycopy/envs/latest/lib/python3.11/site-packages/sphinx/builders/html/__init__.py", line 304, in init_templates
    self.theme = theme_factory.create(themename)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/prettycopy/envs/latest/lib/python3.11/site-packages/sphinx/theming.py", line 230, in create
    return Theme(name, self.themes[name], factory=self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/prettycopy/envs/latest/lib/python3.11/site-packages/sphinx/theming.py", line 75, in __init__
    raise ThemeError(__('theme %r doesn\'t have "theme" setting') % name) from exc
sphinx.errors.ThemeError: theme 'sizzle' doesn't have "theme" setting

Theme error:
theme 'sizzle' doesn't have "theme" setting
```

**Comment by vsajip** [comment]
Please try with version 0.1.3, which I've just uploaded to PyPI. Sorry for the slow response, but for some reason notifications were turned off for this issue, so GitHub never notified me! I only saw this when someone emailed me directly about the same problem.
